apiVersion: v1
kind: Namespace
metadata:
  name: blog-microservices
  labels:
    istio-injection: enabled
---
# Frontend Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: blog-microservices
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: blog-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: BLOG_SERVICE_URL
          value: "http://blog-service:3001"
        - name: COMMENT_SERVICE_URL
          value: "http://comment-service:3002"
        - name: USER_SERVICE_URL
          value: "http://user-service:3003"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3004"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blog-microservices
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    name: http
---
# Blog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: blog-microservices
  labels:
    app: blog-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
      version: v1
  template:
    metadata:
      labels:
        app: blog-service
        version: v1
    spec:
      containers:
      - name: blog-service
        image: blog-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3004"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-microservices
  labels:
    app: blog-service
spec:
  selector:
    app: blog-service
  ports:
  - port: 3001
    targetPort: 3001
    name: http
---
# Comment Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  namespace: blog-microservices
  labels:
    app: comment-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
      version: v1
  template:
    metadata:
      labels:
        app: comment-service
        version: v1
    spec:
      containers:
      - name: comment-service
        image: comment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3004"
        - name: BLOG_SERVICE_URL
          value: "http://blog-service:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: blog-microservices
  labels:
    app: comment-service
spec:
  selector:
    app: comment-service
  ports:
  - port: 3002
    targetPort: 3002
    name: http
---
# User Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: blog-microservices
  labels:
    app: user-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: v1
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
        env:
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3004"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: blog-microservices
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 3003
    targetPort: 3003
    name: http
---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: blog-microservices
  labels:
    app: notification-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: v1
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: blog-microservices
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 3004
    targetPort: 3004
    name: http
