apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blog-service-fault-injection
  namespace: blog-microservices
spec:
  hosts:
  - blog-service
  http:
  - fault:
      delay:
        percentage:
          value: 20
        fixedDelay: 2s
      abort:
        percentage:
          value: 5
        httpStatus: 500
    route:
    - destination:
        host: blog-service
        subset: v1
